name: pockethome
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  flutter:
    sdk: flutter
  flutter_ble_peripheral: ^2.0.1
  flutter_blue_plus: ^2.0.2
  meta: ^1.16.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
